name: Check Product Expiry

on:
  schedule:
    # Executa às 01:15 BRT (22:15 UTC) para teste
    - cron: '15 22 * * *' # 22:15 UTC = 01:15 BRT

jobs:
  check-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to API
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "Content-Type: application/json" \
            $API_URL