name: Check Product Expiry

on:
  schedule:
    # Executa às 01:25 BRT (22:25 UTC) para teste
    - cron: '0 23 * * *' # 23:00 UTC = 02:00 BRT
  workflow_dispatch: # Adiciona execução manual (recomendado)

jobs:
  check-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to API
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "Content-Type: application/json" \
            $API_URL